FROM registry.hub.docker.com/library/python:3.14.7-alpine3.23@sha256:8caa2adfeb414dfe68d8b257f7aea9e205a400521c2b13b2d2e5e731fb8e70e5

RUN pip install --no-cache-dir \
    boto3==1.38.0

ENTRYPOINT [""]
