FROM registry.hub.docker.com/library/python:3.14.4-alpine3.23@sha256:dd4d2bd5b53d9b25a51da13addf2be586beebd5387e289e798e4083d94ca837a

RUN pip install --no-cache-dir \
    boto3==1.38.0

ENTRYPOINT [""]
